#:kivy 2.1.0

<CameraAndRoundButtonLayout>:
    orientation: 'vertical'

<MyRoundButton>:
    size_hint: None, None
    size: 100, 100
    pos_hint: {'center_x': 0.5, 'center_y': 0.1}
    canvas.before:
        Color:
            rgba: 0.2, 0.7, 0.5, 1
        Ellipse:
            pos: self.pos
            size: self.size
    background_color: (0, 0, 0, 0)  # Defina a cor do fundo como transparente